/*
Agent Runtime — Fantasy (Go)

Configuration types parsed from /etc/operator/config.json.
Shared contract with the operator's FantasyExtensionConfig.
*/
package main

// Config is the operator-generated configuration.
type Config struct {
	Runtime         string          `json:"runtime"`
	Providers       []ProviderEntry `json:"providers"`
	PrimaryProvider string          `json:"primaryProvider,omitempty"`
	PrimaryModel    string          `json:"primaryModel"`
	FallbackModels  []string        `json:"fallbackModels,omitempty"`
	TitleModel      string          `json:"titleModel,omitempty"` // fast/cheap model for auto-titling; defaults to primaryModel
	SystemPrompt    string          `json:"systemPrompt,omitempty"`
	BuiltinTools    []string        `json:"builtinTools,omitempty"`
	Tools           []ToolEntry     `json:"tools"`
	MCPServers      []MCPEntry      `json:"mcpServers,omitempty"`
	ToolHooks       *ToolHooksEntry `json:"toolHooks,omitempty"`
	ContextFiles    []ContextEntry  `json:"contextFiles,omitempty"`
	Resources       []ResourceEntry `json:"resources,omitempty"`
	Temperature     *float64        `json:"temperature,omitempty"`
	MaxOutputTokens *int64          `json:"maxOutputTokens,omitempty"`
	MaxSteps        *int            `json:"maxSteps,omitempty"`

	// Permission gate: list of tool names that require user approval before execution.
	// If empty, no tools require approval (all run automatically).
	PermissionTools []string `json:"permissionTools,omitempty"`

	// EnableQuestionTool adds a built-in "question" tool that lets the agent
	// ask the user interactive questions during execution.
	EnableQuestionTool bool `json:"enableQuestionTool,omitempty"`

	// Memory configuration for the Engram shared memory system.
	// When set, the runtime connects to Engram's REST API for persistent memory.
	Memory *MemoryConfig `json:"memory,omitempty"`

	// Discovery & delegation config for this agent.
	// Used by list_task_agents/run_agent to know own scope/callers.
	Discovery *DiscoveryConfig `json:"discovery,omitempty"`

	// Maximum characters allowed in a single tool result before truncation.
	// Prevents large tool outputs (bash, grep, read, fetch) from blowing up
	// the context window. Default: 50000 (~12k tokens).
	MaxToolResultChars int `json:"maxToolResultChars,omitempty"`

	// Fraction of the model's context window to use as the input token budget.
	// When a step's input tokens exceed this fraction, the agent loop stops.
	// Default: 0.75. Valid range: (0, 1).
	BudgetFraction *float64 `json:"budgetFraction,omitempty"`
}

// MemoryConfig configures the Engram memory integration.
// Generated by the operator from Agent.spec.memory.
type MemoryConfig struct {
	// Engram REST API base URL (e.g. "http://engram.agents.svc.cluster.local:7437").
	ServerURL string `json:"serverURL"`
	// Project name used to scope memories (defaults to agent name).
	Project string `json:"project"`
	// Number of recent context entries to inject per turn (default: 5).
	ContextLimit int `json:"contextLimit,omitempty"`
}

// DiscoveryConfig holds this agent's discovery & delegation settings.
// Generated by the operator from Agent.spec.discovery.
type DiscoveryConfig struct {
	Description    string   `json:"description,omitempty"`
	Tags           []string `json:"tags,omitempty"`
	Scope          string   `json:"scope,omitempty"`          // "namespace" (default), "explicit", "hidden"
	AllowedCallers []string `json:"allowedCallers,omitempty"` // only used when scope=explicit
}

// ProviderEntry describes a configured provider.
type ProviderEntry struct {
	Name string `json:"name"`
}

// ToolEntry describes a tool package path (MCP server in OCI).
type ToolEntry struct {
	Name        string `json:"name"`
	Path        string `json:"path"`
	Description string `json:"description,omitempty"`
	Category    string `json:"category,omitempty"`
	UIHint      string `json:"uiHint,omitempty"`
}

// MCPEntry describes an MCP server binding (via gateway sidecar).
type MCPEntry struct {
	Name        string   `json:"name"`
	Port        int      `json:"port"`
	DirectTools []string `json:"directTools,omitempty"`
	Description string   `json:"description,omitempty"`
	Category    string   `json:"category,omitempty"`
	UIHint      string   `json:"uiHint,omitempty"`
}

// ToolHooksEntry holds runtime hook config.
type ToolHooksEntry struct {
	BlockedCommands    []string            `json:"blockedCommands,omitempty"`
	AllowedPaths       []string            `json:"allowedPaths,omitempty"`
	AuditTools         []string            `json:"auditTools,omitempty"`
	MemorySaveRules    []MemorySaveRule    `json:"memorySaveRules,omitempty"`
	ContextInjectTools []ContextInjectRule `json:"contextInjectTools,omitempty"`
}

// MemorySaveRule describes a declarative rule for auto-saving tool results
// as memory observations. When a tool matches, its output (optionally filtered
// by regex) is saved to agentops-memory.
type MemorySaveRule struct {
	// Tool name to match (e.g. "bash", "web_search", "read").
	Tool string `json:"tool"`
	// Regex pattern to match against tool output. If empty, all output is captured.
	// +optional
	MatchOutput string `json:"matchOutput,omitempty"`
	// Map of arg_name → regex pattern. All must match for the rule to fire.
	// +optional
	MatchArgs map[string]string `json:"matchArgs,omitempty"`
	// Observation type to save (e.g. "bugfix", "discovery"). Default: "discovery".
	// +optional
	Type string `json:"type,omitempty"`
	// Scope for the observation. Default: "project".
	// +optional
	Scope string `json:"scope,omitempty"`
}

// ContextInjectRule describes a pre-execution memory query for a tool.
// Before the tool runs, relevant memories are fetched and recorded in the trace.
type ContextInjectRule struct {
	// Tool name to match.
	Tool string `json:"tool"`
	// How to derive the search query. "from_tool_args" (default) uses the tool's
	// primary argument. Any other value is used as a static query string.
	// +optional
	Query string `json:"query,omitempty"`
	// Max number of memory items to fetch. Default: 3.
	// +optional
	Limit int `json:"limit,omitempty"`
}

// ContextEntry describes a context file.
type ContextEntry struct {
	Path string `json:"path"`
}

// ResourceEntry describes an AgentResource bound to this agent.
// Mirrors the operator's AgentResourceEntry from configmap.go.
type ResourceEntry struct {
	Name        string `json:"name"`
	Kind        string `json:"kind"`
	DisplayName string `json:"displayName"`
	Description string `json:"description,omitempty"`
	ReadOnly    bool   `json:"readOnly,omitempty"`
	AutoContext bool   `json:"autoContext,omitempty"`

	// Kind-specific config (one of these will be set)
	GitHub        *ResourceGitHubEntry        `json:"github,omitempty"`
	GitHubOrg     *ResourceGitHubOrgEntry     `json:"githubOrg,omitempty"`
	GitLab        *ResourceGitLabEntry        `json:"gitlab,omitempty"`
	GitLabGroup   *ResourceGitLabGroupEntry   `json:"gitlabGroup,omitempty"`
	Git           *ResourceGitEntry           `json:"git,omitempty"`
	MCP           *ResourceMCPEntry           `json:"mcp,omitempty"`
	S3            *ResourceS3Entry            `json:"s3,omitempty"`
	Documentation *ResourceDocumentationEntry `json:"documentation,omitempty"`
}

type ResourceGitHubEntry struct {
	Owner         string `json:"owner"`
	Repo          string `json:"repo"`
	DefaultBranch string `json:"defaultBranch,omitempty"`
	APIURL        string `json:"apiURL,omitempty"`
}

type ResourceGitHubOrgEntry struct {
	Org        string   `json:"org"`
	RepoFilter []string `json:"repoFilter,omitempty"`
	APIURL     string   `json:"apiURL,omitempty"`
}

type ResourceGitLabEntry struct {
	BaseURL       string `json:"baseURL"`
	Project       string `json:"project"`
	DefaultBranch string `json:"defaultBranch,omitempty"`
}

type ResourceGitLabGroupEntry struct {
	BaseURL  string   `json:"baseURL"`
	Group    string   `json:"group"`
	Projects []string `json:"projects,omitempty"`
}

type ResourceGitEntry struct {
	URL    string `json:"url"`
	Branch string `json:"branch,omitempty"`
}

type ResourceMCPEntry struct {
	URL       string            `json:"url"`
	Transport string            `json:"transport,omitempty"`
	Headers   map[string]string `json:"headers,omitempty"`
}

type ResourceS3Entry struct {
	Bucket   string `json:"bucket"`
	Region   string `json:"region,omitempty"`
	Endpoint string `json:"endpoint,omitempty"`
	Prefix   string `json:"prefix,omitempty"`
}

type ResourceDocumentationEntry struct {
	URLs []string `json:"urls,omitempty"`
}
